### ISSUE TITLE
Crash on opening

### ISSUE THREAD

**Issue by Natemo2625** [brandon3055/BrandonsCore#118] opened 2024-10-08 00:59 UTC
Every time I try to launch Minecraft with this mod enabled it crashes, and the moment I disable it everything works fine
This is the only error log I get
[hs_err_pid916.log](https://github.com/user-attachments/files/17285932/hs_err_pid916.log)

**Comment by FoxMcloud5655** [comment] 2024-10-08 05:02
This crash happens on older AMD cards.  The shader was written with newer GPU features in mind.  NVIDIA GPUs typically don't have these issues.

If this isn't the case, please clarify.  You also need to post what versions of everything you're using;  Minecraft, Forge, CCL, and Brandon's Core at the least.

**Comment by Natemo2625** [comment] 2024-10-08 05:26
Minecraft 1.20.1
Forge 47.3.11
CCL 4.4.0.516
Brandon's Core 3.2.1.302
GPU is an AMD Radeon RX 580 with latest driver installed (released 8/19/24)

**Comment by FoxMcloud5655** [comment] 2024-10-08 08:29
What mod manager are you using?  What's your mod list?  Many mod managers allow you to export a list.

**Comment by Natemo2625** [comment] 2024-10-08 08:47
Curseforge, had to change file extension to send list
[modlist.txt](https://github.com/user-attachments/files/17290579/modlist.txt)

**Comment by FoxMcloud5655** [comment] 2024-10-08 12:03
Try trimming down that mod list temporarily, running only CodeChickenLib and Brandon's Core.  See if that works, and if it does, add Draconic Evolution.  If that works, then keep adding batches of your mods back until something breaks, then start removing until you find the culprit.

Of course, if you run the list with only CodeChickenLib and Brandon's Core and you get another crash (probably not, but stranger things have happened), then we need to do something about it.  Otherwise, it's probably some strange mod conflict.

On that note, I'd remove the GPU memory fix from your list as well as Apotheosis.  The fix is already covered by FerriteCore which ModernFix should have recommended to you if it wasn't included in your mod list.  As for Apotheosis, it conflicts with Draconic Evolution and you'll see weird, unintended interactions, especially involving damage type manipulation.

**Comment by Natemo2625** [comment] 2024-10-08 20:34
I do in fact have FerriteCore, removed GPUMemoryFix. Also I don't have a lot of time rn, but I did narrow it down to a mod within the C to F range, anything you can think of that could be possibly causing it? If not I can continue checking sometime later.

**Comment by Natemo2625** [comment] 2024-10-08 23:28
I have located the conflicting mod, it's somehow conflicting with FTB Chunks, I have version 2001.3.1 currently

Edit: I kept Apotheosis in, would prefer to keep that mod, not causing any immediate issues anyway

**Comment by FoxMcloud5655** [comment] 2024-10-09 00:08
Then this seems to be a duplicate of https://github.com/Draconic-Inc/Draconic-Evolution/issues/1826

**Closed as not planned by FoxMcloud5655** 2024-10-09 00:08 UTC

**Comment by Natemo2625** [comment] 2024-10-09 00:13
That's unfortunate, didn't wanna have to choose between mods, they seemed to work fine together in 1.16.5, so I wonder what changed

**Comment by FoxMcloud5655** [comment] 2024-10-09 00:54
Right?  We have no idea what's causing it either.

**Comment by Natemo2625** [comment] 2024-10-09 06:07
I haven't seen anything that helps in the log tbh, maybe FTB could figure out why? Or help figure out why anyway
